# Generated by Django 5.0.2 on 2024-04-04 01:36

import gp8app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp8app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='active_date',
            field=models.DateField(db_column='Active_Date', default=gp8app.models.get_current_date),
        ),
    ]
