# Generated by Django 5.0.2 on 2024-04-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp8app', '0002_alter_users_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncar',
            name='vin',
            field=models.ForeignKey(blank=True, db_column='VIN', null=True, on_delete=django.db.models.deletion.CASCADE, to='gp8app.car'),
        ),
    ]
