# Generated by Django 5.0.2 on 2024-04-10 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp8app', '0003_alter_auctioncar_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedan',
            name='vin',
            field=models.OneToOneField(db_column='VIN', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gp8app.car'),
        ),
    ]
